// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ARUMANDESU/go-test-kami/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Reserver is an autogenerated mock type for the Reserver type
type Reserver struct {
	mock.Mock
}

// ReserveRoom provides a mock function with given fields: ctx, _a1
func (_m *Reserver) ReserveRoom(ctx context.Context, _a1 domain.Reservation) (domain.Reservation, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReserveRoom")
	}

	var r0 domain.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Reservation) (domain.Reservation, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Reservation) domain.Reservation); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Reservation) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReserver creates a new instance of Reserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reserver {
	mock := &Reserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
