CREATE TABLE reservations (
    id TEXT PRIMARY KEY, -- UUID
    room_id TEXT NOT NULL, -- UUID
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);